/* eslint-disable react/function-component-definition */
import './globals.css'
import Navbar from '@src/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-main">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
